# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file into the container and install dependencies in one layer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    apt-get update

    # Copy the rest of the application code into the container
COPY . .

# Set the environment variables
ENV AWS_REGION=us-east-1
ENV S3_BUCKET_NAME_DATA=uwingine-data
ENV DYNAMODB_TABLE_NAME=Uwingine-Metadata
ENV GROQ_API_KEY=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
ENV GOOGLE_API_KEY=AIzaSyAADo2JDAwzCqmjnNux8wmcN5t-vqyIcKM
ENV HF_TOKEN=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
ENV LANGCHAIN_API_KEY=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

# Run the Python script
CMD ["python", "generate_llm_embedding.py"]